apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: firstcontainer
      image: dignity26/imagename
      env:
        - name: myname
          value: ajit

        - name: age
          value: twentynine
      
      args: ["sleep","50"]

    - name: secondcontainer
      image: coolgourav147/nginx-custom
