apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: containername
      image: dignity26/imagename
      imagePullPolicy: Never
      resources:
        requests:
          memory: 200Mi
          cpu: 100m
        limits:
          memory:
          memory: 500Mi
          cpu: 400m
