apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: containername
      image: dignity26/imagename
      envFrom:  # to inject all Env variable from secret
        - secretRef:
            name: myenvsec
      env:
        - name: mysecretvariable
          valueFrom:
            secretKeyRef:
              key: variable1 #only single variable 
              name: myenvsec #nameof secret
