apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: containername
      image: dignity26/imagename
      volumeMounts:
        - name: testsecret
          mountPath: "/secrets"
          readOnly: true

  volumes:
    - name: testsecret
      secret:
        secretName: envsecret
        items:
          - key: variable1
            path: "variable1here"
