apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: containername
      image: dignity26/imagename
  tolerations:
    - effect: "NoSchedule"
      key: "mysize"
      operator: "Equal"
      value: "mysize"
