apiVersion: v1
kind: Pod
metadata:
  name: test-vol
spec:
  containers:
    - image: coolgourav147/nginx-custom
      name: test-container
      volumeMounts: 
       - mountPath: /Data
         name: first-volume
  volumes: 
  - name: first-volume
    awsElasticBlockStore:
      volumeID: "volume_ID"
      fsType: ext4
